language: php
php:
  - "5.4"
branches:
  only:
    - master
cache:
  directories:
  - vendor
before_script:
  - php -v
  - phpunit --version
  - curl -sS https://getcomposer.org/installer | php
  - chmod +x composer.phar
  - php composer.phar install
script: phpunit -c src/
notifications:
  email:
    - vinyvicente@gmail.com